// SQL Mastery curriculum: comprehensive modules for analytics + data engineering.

import type { MasteryModule } from "./seed-mastery-python";

export const sqlMasteryModules: MasteryModule[] = [
  {
    slug: "sql-foundations",
    title: "SQL Foundations",
    description: "SELECT, WHERE, GROUP BY, JOINs, and aggregations — the building blocks of all SQL queries.",
    orderIndex: 1,
    isPremium: false,
    lessonCount: 5,
    estimatedHours: 4,
    difficultyLevel: "beginner",
    learningObjectives: [
      "Write complex SELECT queries",
      "Master all JOIN types",
      "Group and aggregate data",
      "Filter with WHERE and HAVING",
      "Handle NULLs correctly",
    ],
    lessons: [
      {
        slug: "select-filtering",
        title: "SELECT & Filtering",
        content: "# SELECT Fundamentals\n\n```sql\nSELECT user_id, email, created_at\nFROM users\nWHERE is_active = TRUE\n  AND created_at >= '2024-01-01'\nORDER BY created_at DESC;\n```\n\n**Tips:**\n- Use `IS NULL` not `= NULL`\n- `LIMIT` before you run heavy queries\n- `EXPLAIN` to see what the DB will do",
        type: "reading", orderIndex: 1, mins: 15, xp: 20,
      },
      {
        slug: "joins-basics",
        title: "JOINs Demystified",
        content: "# SQL Joins\n\n```sql\n-- INNER JOIN: only matching rows from both tables\nSELECT u.email, o.total\nFROM users u\nINNER JOIN orders o ON u.id = o.user_id;\n\n-- LEFT JOIN: all users, even with no orders\nSELECT u.email, COUNT(o.id) as orders\nFROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nGROUP BY u.email;\n```\n\n**Key:** INNER = intersection, LEFT = keep all left rows. RIGHT JOIN exists but is almost never used — flip the table order and use LEFT instead.",
        type: "reading", orderIndex: 2, mins: 25, xp: 25,
      },
      {
        slug: "aggregations-basic",
        title: "Aggregations & GROUP BY",
        content: "# Aggregations\n\n```sql\nSELECT\n    DATE_TRUNC('month', event_ts) as month,\n    COUNT(*) as events,\n    COUNT(DISTINCT user_id) as unique_users,\n    SUM(revenue) as total_revenue\nFROM events\nGROUP BY 1\nHAVING COUNT(*) > 100  -- Filter AFTER grouping\nORDER BY 1 DESC;\n```\n\n**Remember:** `WHERE` filters before grouping, `HAVING` filters after.",
        type: "reading", orderIndex: 3, mins: 20, xp: 25,
      },
      {
        slug: "null-handling",
        title: "NULLs & Three-Valued Logic",
        content: "# NULL is not zero\n\n`NULL = NULL` is **NULL**, not TRUE. SQL uses three-valued logic: TRUE / FALSE / UNKNOWN.\n\n```sql\n-- Wrong\nWHERE deleted_at = NULL          -- always UNKNOWN → no rows\n\n-- Right\nWHERE deleted_at IS NULL\n\n-- Coerce in aggregations\nSELECT COALESCE(country, 'UNKNOWN') as country, COUNT(*)\nFROM users\nGROUP BY 1;\n\n-- COUNT gotcha\nSELECT COUNT(*),         -- counts rows, including NULL\n       COUNT(country)    -- counts non-NULL countries only\nFROM users;\n```\n\nForgetting NULL semantics is the #1 cause of silently-wrong reports.",
        type: "reading", orderIndex: 4, mins: 20, xp: 30,
      },
      {
        slug: "subqueries",
        title: "Subqueries & EXISTS",
        content: "# Subqueries\n\n```sql\n-- Scalar subquery\nSELECT u.email,\n       (SELECT COUNT(*) FROM orders o WHERE o.user_id = u.id) as orders\nFROM users u;\n\n-- IN with subquery\nSELECT * FROM users\nWHERE id IN (SELECT user_id FROM orders WHERE total > 1000);\n\n-- EXISTS — usually faster than IN for large sets\nSELECT * FROM users u\nWHERE EXISTS (\n    SELECT 1 FROM orders o WHERE o.user_id = u.id AND o.total > 1000\n);\n```\n\n`EXISTS` short-circuits the moment it finds one row. `IN` builds the full set first.",
        type: "reading", orderIndex: 5, mins: 25, xp: 35,
      },
    ],
  },
  {
    slug: "sql-joins-aggregations",
    title: "Joins & Aggregations Deep Dive",
    description: "Outer joins, anti joins, lateral joins, and aggregation gotchas analytics engineers hit weekly.",
    orderIndex: 2,
    isPremium: false,
    lessonCount: 4,
    estimatedHours: 3,
    difficultyLevel: "intermediate",
    learningObjectives: [
      "Choose the right join type",
      "Write anti-joins to find missing rows",
      "Use LATERAL / cross joins for per-row computation",
      "Avoid double-counting in many-to-many joins",
    ],
    lessons: [
      {
        slug: "join-types",
        title: "All the Join Types",
        content: "# Beyond INNER and LEFT\n\n```sql\n-- FULL OUTER: rows from both sides, NULLs where no match\nSELECT a.id, b.id\nFROM a FULL OUTER JOIN b ON a.key = b.key;\n\n-- CROSS JOIN: cartesian product (every combination)\nSELECT u.id, p.id\nFROM users u CROSS JOIN products p;\n\n-- Self join — find users who share a referrer\nSELECT a.email AS user, b.email AS sibling\nFROM users a JOIN users b\n  ON a.referrer_id = b.referrer_id\n WHERE a.id <> b.id;\n```",
        type: "reading", orderIndex: 1, mins: 25, xp: 35,
      },
      {
        slug: "anti-joins",
        title: "Anti-Joins: Find What's Missing",
        content: "# Three ways to write 'not in'\n\n```sql\n-- Users who never ordered:\n\n-- 1. NOT EXISTS (recommended — NULL-safe, fast)\nSELECT * FROM users u\nWHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.user_id = u.id);\n\n-- 2. LEFT JOIN ... WHERE IS NULL (also fine)\nSELECT u.*\nFROM users u\nLEFT JOIN orders o ON o.user_id = u.id\nWHERE o.user_id IS NULL;\n\n-- 3. NOT IN (DANGEROUS — breaks if subquery returns any NULL)\nSELECT * FROM users\nWHERE id NOT IN (SELECT user_id FROM orders);  -- silently returns 0 rows if user_id has NULLs!\n```\n\nUse `NOT EXISTS`. Always.",
        type: "reading", orderIndex: 2, mins: 25, xp: 35,
      },
      {
        slug: "lateral-joins",
        title: "LATERAL: Per-Row Subqueries",
        content: "# LATERAL joins\n\nA LATERAL subquery can reference columns from earlier FROM items — like a `for each row, run this query`.\n\n```sql\n-- Top 3 most recent orders per user\nSELECT u.id, u.email, o.order_id, o.ordered_at\nFROM users u\nCROSS JOIN LATERAL (\n    SELECT order_id, ordered_at\n    FROM orders\n    WHERE user_id = u.id\n    ORDER BY ordered_at DESC\n    LIMIT 3\n) o;\n```\n\nWithout LATERAL you'd need a window function and an outer filter — LATERAL is often clearer.",
        type: "reading", orderIndex: 3, mins: 25, xp: 40,
      },
      {
        slug: "double-counting",
        title: "Avoiding Double Counts",
        content: "# Many-to-many joins inflate aggregates\n\n```sql\n-- WRONG — if a user has 3 tags, their revenue is counted 3x\nSELECT u.id, SUM(o.total) AS revenue\nFROM users u\nJOIN orders o   ON o.user_id = u.id\nJOIN user_tags t ON t.user_id = u.id\nGROUP BY u.id;\n\n-- RIGHT — aggregate orders separately, then join tags\nWITH rev AS (\n    SELECT user_id, SUM(total) AS revenue\n    FROM orders GROUP BY user_id\n)\nSELECT u.id, r.revenue, ARRAY_AGG(DISTINCT t.tag) AS tags\nFROM users u\nLEFT JOIN rev r       ON r.user_id = u.id\nLEFT JOIN user_tags t ON t.user_id = u.id\nGROUP BY u.id, r.revenue;\n```\n\n**Rule of thumb:** if the join introduces a new dimension, aggregate first.",
        type: "reading", orderIndex: 4, mins: 25, xp: 40,
      },
    ],
  },
  {
    slug: "sql-window-functions",
    title: "Window Functions",
    description: "Running totals, ranks, lag/lead, and frame clauses — the most powerful feature in modern SQL.",
    orderIndex: 3,
    isPremium: true,
    lessonCount: 5,
    estimatedHours: 4,
    difficultyLevel: "intermediate",
    learningObjectives: [
      "Use OVER, PARTITION BY, and ORDER BY",
      "Compute running totals and moving averages",
      "Rank rows with ROW_NUMBER, RANK, DENSE_RANK",
      "Compare rows to neighbors with LAG and LEAD",
      "Customize windows with frame clauses",
    ],
    lessons: [
      {
        slug: "window-intro",
        title: "OVER, PARTITION BY, ORDER BY",
        content: "# Window functions\n\nThe most powerful SQL feature for analytics:\n\n```sql\nSELECT\n    order_id,\n    user_id,\n    revenue,\n    SUM(revenue) OVER (PARTITION BY user_id ORDER BY order_date) AS running_total,\n    RANK() OVER (PARTITION BY user_id ORDER BY revenue DESC)     AS rank_in_user,\n    LAG(revenue) OVER (PARTITION BY user_id ORDER BY order_date) AS prev_revenue\nFROM orders;\n```\n\n`PARTITION BY` = group, `ORDER BY` = sort within group. The query keeps every row — unlike GROUP BY, which collapses rows.",
        type: "reading", orderIndex: 1, mins: 25, xp: 40,
      },
      {
        slug: "ranking",
        title: "ROW_NUMBER, RANK, DENSE_RANK",
        content: "# Three ways to rank\n\n```sql\nSELECT name, score,\n       ROW_NUMBER() OVER (ORDER BY score DESC) rn,\n       RANK()       OVER (ORDER BY score DESC) rk,\n       DENSE_RANK() OVER (ORDER BY score DESC) dr\nFROM players;\n```\n\nGiven scores 100, 95, 95, 90:\n\n| score | row_number | rank | dense_rank |\n|---|---|---|---|\n| 100 | 1 | 1 | 1 |\n| 95  | 2 | 2 | 2 |\n| 95  | 3 | 2 | 2 |\n| 90  | 4 | 4 | 3 |\n\nUse `ROW_NUMBER` for unique tiebreaker IDs, `DENSE_RANK` for placement.",
        type: "reading", orderIndex: 2, mins: 20, xp: 35,
      },
      {
        slug: "lag-lead",
        title: "LAG & LEAD: Compare to Neighbors",
        content: "# Period-over-period comparisons\n\n```sql\nSELECT\n    month,\n    revenue,\n    LAG(revenue)  OVER (ORDER BY month) AS prev_month,\n    LEAD(revenue) OVER (ORDER BY month) AS next_month,\n    (revenue - LAG(revenue) OVER (ORDER BY month))::float\n        / NULLIF(LAG(revenue) OVER (ORDER BY month), 0) AS mom_growth\nFROM monthly_revenue;\n```\n\n`NULLIF(x, 0)` prevents divide-by-zero. Use `LAG(col, 12)` for year-over-year.",
        type: "reading", orderIndex: 3, mins: 25, xp: 40,
      },
      {
        slug: "frame-clauses",
        title: "Frame Clauses: ROWS vs RANGE",
        content: "# Customizing the window frame\n\nA frame clause defines exactly which rows the function aggregates over.\n\n```sql\n-- 7-day moving average (last 6 days + current)\nSELECT day, revenue,\n       AVG(revenue) OVER (\n           ORDER BY day\n           ROWS BETWEEN 6 PRECEDING AND CURRENT ROW\n       ) AS ma_7d\nFROM daily_revenue;\n\n-- Cumulative sum from the start\nSELECT day, revenue,\n       SUM(revenue) OVER (\n           ORDER BY day\n           ROWS UNBOUNDED PRECEDING\n       ) AS cumulative\nFROM daily_revenue;\n```\n\nDefault frame for ordered windows is `RANGE UNBOUNDED PRECEDING TO CURRENT ROW` — usually what you want, but not always.",
        type: "reading", orderIndex: 4, mins: 25, xp: 45,
      },
      {
        slug: "qualify-keep-top-n",
        title: "QUALIFY: Top-N Per Group",
        content: "# Top N per group, the easy way\n\n```sql\n-- Snowflake / BigQuery / DuckDB: QUALIFY\nSELECT user_id, order_id, total\nFROM orders\nQUALIFY ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY total DESC) <= 3;\n\n-- Postgres: subquery + WHERE\nSELECT * FROM (\n    SELECT user_id, order_id, total,\n           ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY total DESC) AS rn\n    FROM orders\n) t\nWHERE rn <= 3;\n```\n\n`QUALIFY` is to window functions what `HAVING` is to GROUP BY. Postgres doesn't have it (yet) — wrap in a CTE/subquery.",
        type: "reading", orderIndex: 5, mins: 20, xp: 40,
      },
    ],
  },
  {
    slug: "sql-for-analytics",
    title: "SQL for Analytics Engineering",
    description: "Cohort retention, funnel analysis, time-series, sessionization, and pivot patterns.",
    orderIndex: 4,
    isPremium: true,
    lessonCount: 5,
    estimatedHours: 4,
    difficultyLevel: "intermediate",
    learningObjectives: [
      "Build cohort retention analyses",
      "Write funnel queries",
      "Sessionize event streams",
      "Pivot rows into columns",
      "Bucket and percentile distributions",
    ],
    lessons: [
      {
        slug: "cohort-analysis",
        title: "Cohort Retention Analysis",
        content: "# Cohort retention\n\nMeasure how many users return month-over-month after they first signed up:\n\n```sql\nWITH cohorts AS (\n    SELECT user_id,\n           DATE_TRUNC('month', MIN(created_at)) AS cohort_month\n    FROM users GROUP BY user_id\n),\nactivity AS (\n    SELECT user_id,\n           DATE_TRUNC('month', event_ts) AS active_month\n    FROM events\n    GROUP BY 1, 2\n)\nSELECT\n    c.cohort_month,\n    EXTRACT(MONTH FROM AGE(a.active_month, c.cohort_month)) AS month_number,\n    COUNT(DISTINCT a.user_id)::float\n        / COUNT(DISTINCT c.user_id) AS retention\nFROM cohorts c\nLEFT JOIN activity a USING (user_id)\nGROUP BY 1, 2\nORDER BY 1, 2;\n```\n\nThe shape of the cohort triangle tells you whether your product retains.",
        type: "reading", orderIndex: 1, mins: 30, xp: 50,
      },
      {
        slug: "funnel-analysis",
        title: "Funnel Conversion",
        content: "# Funnel queries\n\n```sql\nWITH steps AS (\n    SELECT user_id, MIN(CASE WHEN event = 'visit'    THEN ts END) AS s1,\n                    MIN(CASE WHEN event = 'signup'   THEN ts END) AS s2,\n                    MIN(CASE WHEN event = 'purchase' THEN ts END) AS s3\n    FROM events\n    WHERE event IN ('visit', 'signup', 'purchase')\n    GROUP BY user_id\n)\nSELECT\n    COUNT(s1)                    AS visited,\n    COUNT(s2)                    AS signed_up,\n    COUNT(s3)                    AS purchased,\n    COUNT(s2)::float / COUNT(s1) AS visit_to_signup,\n    COUNT(s3)::float / COUNT(s2) AS signup_to_purchase\nFROM steps\nWHERE s2 > s1 OR s2 IS NULL    -- enforce ordering\n  AND (s3 > s2 OR s3 IS NULL);\n```\n\nEnforcing event ordering matters — otherwise you count 'purchase before signup' as a conversion.",
        type: "reading", orderIndex: 2, mins: 30, xp: 50,
      },
      {
        slug: "sessionization",
        title: "Sessionization with Window Functions",
        content: "# Build sessions from raw events\n\nA session = consecutive events from a user with < 30 min gaps.\n\n```sql\nWITH gaps AS (\n    SELECT user_id, ts,\n           ts - LAG(ts) OVER (PARTITION BY user_id ORDER BY ts) AS gap\n    FROM events\n),\nflagged AS (\n    SELECT user_id, ts,\n           CASE WHEN gap IS NULL OR gap > INTERVAL '30 minutes'\n                THEN 1 ELSE 0 END AS is_new_session\n    FROM gaps\n)\nSELECT user_id, ts,\n       SUM(is_new_session) OVER (PARTITION BY user_id ORDER BY ts) AS session_id\nFROM flagged;\n```\n\nThe `SUM(0/1) OVER ORDER BY` is the canonical 'gaps and islands' trick.",
        type: "reading", orderIndex: 3, mins: 30, xp: 50,
      },
      {
        slug: "pivots",
        title: "Pivot Rows to Columns",
        content: "# Conditional aggregation pivot\n\nPortable across every dialect:\n\n```sql\nSELECT\n    DATE_TRUNC('month', ts) AS month,\n    SUM(CASE WHEN channel = 'organic' THEN revenue ELSE 0 END) AS organic,\n    SUM(CASE WHEN channel = 'paid'    THEN revenue ELSE 0 END) AS paid,\n    SUM(CASE WHEN channel = 'email'   THEN revenue ELSE 0 END) AS email\nFROM orders\nGROUP BY 1\nORDER BY 1;\n```\n\nFor dynamic pivots (unknown channels) you need application code or `tablefunc.crosstab` (Postgres).",
        type: "reading", orderIndex: 4, mins: 20, xp: 40,
      },
      {
        slug: "percentiles-buckets",
        title: "Percentiles & Bucketing",
        content: "# Distributions\n\n```sql\n-- Percentiles\nSELECT\n    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY total) AS p50,\n    PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY total) AS p95,\n    PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY total) AS p99\nFROM orders;\n\n-- Equal-width buckets (histograms)\nSELECT WIDTH_BUCKET(total, 0, 1000, 10) AS bucket, COUNT(*)\nFROM orders GROUP BY 1 ORDER BY 1;\n\n-- Equal-frequency buckets (NTILE = quantiles)\nSELECT NTILE(4) OVER (ORDER BY total) AS quartile, COUNT(*)\nFROM orders GROUP BY 1;\n```\n\nReporting only `AVG()` hides every long-tail problem. Always pair with p50/p95/p99.",
        type: "reading", orderIndex: 5, mins: 25, xp: 45,
      },
    ],
  },
  {
    slug: "sql-performance",
    title: "SQL Performance & Indexing",
    description: "EXPLAIN plans, indexes, partition pruning, and statistics — find and fix slow queries.",
    orderIndex: 5,
    isPremium: true,
    lessonCount: 4,
    estimatedHours: 3,
    difficultyLevel: "advanced",
    learningObjectives: [
      "Read EXPLAIN ANALYZE output",
      "Pick the right index type",
      "Use partial and composite indexes",
      "Understand partition pruning",
    ],
    lessons: [
      {
        slug: "explain-plans",
        title: "Reading EXPLAIN Plans",
        content: "# EXPLAIN ANALYZE\n\n```sql\nEXPLAIN (ANALYZE, BUFFERS)\nSELECT u.email, COUNT(o.id)\nFROM users u\nLEFT JOIN orders o ON o.user_id = u.id\nWHERE u.country = 'US'\nGROUP BY u.email;\n```\n\nWhat to look for, top to bottom:\n\n1. **Sequential Scan on a big table?** → likely missing index\n2. **Rows estimate vs actual** wildly different? → ANALYZE the table to refresh stats\n3. **Hash Join with very high memory** → consider an index for nested-loop join instead\n4. **High Buffers: read** → cold cache or index missing\n\nThe goal is `Index Scan` or `Index Only Scan` on filter columns.",
        type: "reading", orderIndex: 1, mins: 30, xp: 50,
      },
      {
        slug: "index-types",
        title: "Index Types",
        content: "# Picking the right index\n\n| Type | Use case |\n|---|---|\n| B-tree (default) | equality + range on scalar columns |\n| Hash | equality only — niche, B-tree usually better |\n| GIN | full-text search, JSONB, array contains |\n| GiST | geo (PostGIS), nearest-neighbor |\n| BRIN | very large append-only tables (logs, time-series) |\n\n```sql\n-- B-tree on a foreign key\nCREATE INDEX ON orders (user_id);\n\n-- GIN for JSONB key search\nCREATE INDEX ON events USING GIN (properties jsonb_path_ops);\n\n-- BRIN for huge time-series\nCREATE INDEX ON events USING BRIN (event_ts);\n```\n\nForeign key columns are almost always worth indexing — joins use them constantly.",
        type: "reading", orderIndex: 2, mins: 25, xp: 45,
      },
      {
        slug: "composite-partial",
        title: "Composite & Partial Indexes",
        content: "# Composite indexes — column order matters\n\n```sql\nCREATE INDEX ON orders (user_id, ordered_at DESC);\n```\n\nThis index can satisfy:\n- `WHERE user_id = 42`\n- `WHERE user_id = 42 AND ordered_at > '...'`\n- `WHERE user_id = 42 ORDER BY ordered_at DESC`\n\nIt **cannot** satisfy `WHERE ordered_at > '...'` alone — you'd need a separate index.\n\n## Partial indexes — only index rows you query\n\n```sql\nCREATE INDEX ON orders (user_id) WHERE status = 'pending';\n```\n\nIf 99% of orders are 'completed' but you only ever query 'pending', a partial index is 100x smaller and faster.",
        type: "reading", orderIndex: 3, mins: 25, xp: 50,
      },
      {
        slug: "partitioning-perf",
        title: "Partitioning for Scale",
        content: "# Range partitioning\n\nFor tables > 100M rows, partitioning lets the planner skip entire chunks (partition pruning).\n\n```sql\nCREATE TABLE events (\n    id BIGSERIAL,\n    user_id BIGINT NOT NULL,\n    event_ts TIMESTAMPTZ NOT NULL,\n    properties JSONB\n) PARTITION BY RANGE (event_ts);\n\nCREATE TABLE events_2024_q1 PARTITION OF events\n    FOR VALUES FROM ('2024-01-01') TO ('2024-04-01');\nCREATE TABLE events_2024_q2 PARTITION OF events\n    FOR VALUES FROM ('2024-04-01') TO ('2024-07-01');\n\nCREATE INDEX ON events_2024_q1 (user_id);\nCREATE INDEX ON events_2024_q2 (user_id);\n```\n\nA query with `WHERE event_ts BETWEEN '2024-04-15' AND '2024-04-20'` will scan only `events_2024_q2`. Always include the partition key in your WHERE clause.",
        type: "reading", orderIndex: 4, mins: 30, xp: 55,
      },
    ],
  },
  {
    slug: "sql-database-design",
    title: "Database Design",
    description: "Normalization, denormalization, surrogate vs natural keys, and modeling for OLTP vs OLAP.",
    orderIndex: 6,
    isPremium: true,
    lessonCount: 4,
    estimatedHours: 3,
    difficultyLevel: "intermediate",
    learningObjectives: [
      "Apply 3NF normalization",
      "Decide when to denormalize",
      "Pick keys deliberately",
      "Model star and snowflake schemas",
    ],
    lessons: [
      {
        slug: "normalization",
        title: "Normalization (1NF → 3NF)",
        content: "# Normalize OLTP, denormalize OLAP\n\n- **1NF** — atomic columns, no repeating groups (no comma-separated lists in a single field)\n- **2NF** — every non-key column depends on the whole primary key\n- **3NF** — non-key columns depend only on the key, not on each other\n\n```sql\n-- Not 3NF: city/state depend on zipcode, not user\nusers(id, email, zipcode, city, state)\n\n-- 3NF\nusers(id, email, zipcode)\nzipcodes(zipcode, city, state)\n```\n\nAim for 3NF in operational stores. You'll denormalize again for analytics — but start from a clean model.",
        type: "reading", orderIndex: 1, mins: 25, xp: 40,
      },
      {
        slug: "keys",
        title: "Surrogate vs Natural Keys",
        content: "# Pick keys deliberately\n\n| | Surrogate | Natural |\n|---|---|---|\n| Example | `id BIGSERIAL` / `uuid` | `email`, `iso_country_code` |\n| Stable? | Yes — never changes | No — emails change, countries split |\n| Joinable? | Always equal-by-int | Equal-by-string (slower) |\n| Migrations | Easy | Painful |\n\n**Default to surrogate keys.** Use natural keys only for small, truly stable lookup tables (e.g. ISO country codes).\n\nFor distributed inserts, prefer `uuid` (or ULID) over autoincrement to avoid contention on the sequence.",
        type: "reading", orderIndex: 2, mins: 20, xp: 40,
      },
      {
        slug: "star-snowflake",
        title: "Star & Snowflake Schemas",
        content: "# Dimensional modeling\n\nA star schema:\n\n```\n        dim_date            dim_product\n              \\               /\n               fact_orders\n              /               \\\n        dim_user             dim_channel\n```\n\n- **Fact** — measurable events (orders, page_views) with foreign keys to dims\n- **Dimension** — descriptive context (users, products, dates) — usually wide and denormalized\n\nA snowflake schema normalizes dimensions further (e.g. `dim_product → dim_category`). Use it sparingly — extra joins slow the typical analytics query.\n\nFor most warehouses (Snowflake, BigQuery, Databricks), **prefer star schemas with wide denormalized dims** — storage is cheap, joins are expensive.",
        type: "reading", orderIndex: 3, mins: 25, xp: 45,
      },
      {
        slug: "scd",
        title: "Slowly Changing Dimensions (SCD)",
        content: "# Tracking history in dimensions\n\nA user changes their email — what does the warehouse remember?\n\n- **Type 1**: overwrite — keep only the latest value\n- **Type 2**: insert a new row with `valid_from`/`valid_to` — keep full history\n- **Type 3**: keep `current_value` and `previous_value` columns — limited history\n\nSCD2 example:\n\n```sql\nCREATE TABLE dim_user (\n    user_sk    BIGSERIAL PRIMARY KEY,        -- surrogate, stable per version\n    user_id    BIGINT NOT NULL,              -- natural id\n    email      TEXT NOT NULL,\n    plan       TEXT NOT NULL,\n    valid_from TIMESTAMPTZ NOT NULL,\n    valid_to   TIMESTAMPTZ,                  -- NULL = current\n    is_current BOOLEAN GENERATED ALWAYS AS (valid_to IS NULL) STORED\n);\n```\n\nFacts join to dimensions on the `*_sk` surrogate as of the fact's timestamp — this preserves *the user's plan at the time of the order*, not their plan today.",
        type: "reading", orderIndex: 4, mins: 30, xp: 50,
      },
    ],
  },
];
