import { Router, type IRouter } from "express";
import healthRouter from "./health";
import domainsRouter from "./domains";
import coursesRouter from "./courses";
import projectsRouter from "./projects";
import userRouter from "./user";
import aiRouter from "./ai";
import billingRouter from "./billing";
import executeRouter from "./execute";
import leaderboardRouter from "./leaderboard";
import modulesRouter from "./modules";
import waitlistRouter from "./waitlist";
import runsRouter from "./runs";
import publicProfileRouter from "./public-profile";
import certVerifyRouter from "./cert-verify";
import hintsRouter from "./hints";
import adminRouter from "./admin";
import enrollmentRouter from "./enrollment";
import dashboardRouter from "./dashboard";
import onboardingRouter from "./onboarding";

const router: IRouter = Router();

router.use(healthRouter);
router.use(domainsRouter);
router.use(coursesRouter);
router.use(projectsRouter);
router.use(userRouter);
router.use(aiRouter);
router.use(billingRouter);
router.use(executeRouter);
router.use(leaderboardRouter);
router.use(modulesRouter);
router.use(waitlistRouter);
router.use(runsRouter);
router.use(publicProfileRouter);
router.use(certVerifyRouter);
router.use(hintsRouter);
router.use(adminRouter);
router.use(enrollmentRouter);
router.use(dashboardRouter);
router.use(onboardingRouter);

export default router;
