#!/usr/bin/env python3
"""Build the Atlas mini-report HTML archive.

Reads every `src/*.md` (sorted by filename), renders each to a standalone styled
HTML page, and assembles an `index.html` that embeds all reports with a sticky
table-of-contents. To add a FUTURE mini-report: drop a new `src/NN-<slug>.md`
file (first line `# Title`, optional second line `META: <date> | <status>`) and
re-run `python build.py`.

No repo dependency — uses the `markdown` pip package as a local dev tool.
"""
from __future__ import annotations
import glob, html, os, re
import markdown

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "src")

MD_EXT = ["tables", "fenced_code", "sane_lists", "toc", "attr_list"]

PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<link rel="stylesheet" href="{css}">
</head>
<body>
<main class="report">
<p class="back"><a href="{index}">&larr; All mini-reports</a></p>
{body}
</main>
</body>
</html>
"""

INDEX = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Atlas — Claude Code Mini-Reports to ChatGPT</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
<aside class="toc">
<h2>Mini-Reports</h2>
<p class="sub">Claude Code &rarr; ChatGPT</p>
<nav>{nav}</nav>
<p class="genline">{count} reports &middot; generated by <code>build.py</code></p>
</aside>
<main class="index">
<header class="masthead">
<h1>Atlas — Claude Code Mini-Reports</h1>
<p>Structured 12-section reports returned after each ChatGPT-directed task on the Atlas build.
Each report is also available as a standalone page (links in the sidebar). Newest work is the
<code>csv_set_equal</code> server-grading arc: 57B-prereq &rarr; 0.x &rarr; 0.y &rarr; 0.z &rarr; 0.zz &rarr; 57B-flip.</p>
</header>
{sections}
</main>
</body>
</html>
"""


def parse(path: str):
    with open(path, "r", encoding="utf-8") as f:
        raw = f.read()
    lines = raw.splitlines()
    title = "Untitled"
    meta = ""
    body_lines = lines
    if lines and lines[0].startswith("# "):
        title = lines[0][2:].strip()
        body_lines = lines[1:]
    # optional META: line
    rest = [l for l in body_lines if l.strip()]
    if rest and rest[0].startswith("META:"):
        meta = rest[0][len("META:"):].strip()
        # drop the first non-empty META line from the body
        idx = body_lines.index(rest[0])
        body_lines = body_lines[:idx] + body_lines[idx + 1:]
    body_md = "\n".join(body_lines).strip()
    body_html = markdown.markdown(body_md, extensions=MD_EXT)
    return title, meta, body_html


def slug(path: str) -> str:
    base = os.path.splitext(os.path.basename(path))[0]
    return re.sub(r"^\d+-", "", base)


def main() -> None:
    files = sorted(glob.glob(os.path.join(SRC, "*.md")))
    if not files:
        print("no src/*.md found")
        return
    nav_items, sections = [], []
    for path in files:
        sid = slug(path)
        title, meta, body_html = parse(path)
        meta_html = f'<p class="meta">{html.escape(meta)}</p>' if meta else ""
        header = f'<header class="rpt-head"><h1>{html.escape(title)}</h1>{meta_html}</header>'
        # standalone page
        page = PAGE.format(
            title=html.escape(title), css="style.css", index="index.html",
            body=header + body_html,
        )
        with open(os.path.join(HERE, f"{sid}.html"), "w", encoding="utf-8") as f:
            f.write(page)
        # index section + nav
        nav_label = title.split("—")[0].strip() if "—" in title else title
        nav_meta = f'<span class="navmeta">{html.escape(meta.split("|")[0].strip())}</span>' if meta else ""
        nav_items.append(
            f'<a href="#{sid}"><span class="navtitle">{html.escape(nav_label)}</span>{nav_meta}</a>'
        )
        sections.append(
            f'<section id="{sid}" class="report card">'
            f'<p class="permalink"><a href="{sid}.html">open standalone &rarr;</a></p>'
            f'{header}{body_html}</section>'
        )
    index = INDEX.format(nav="\n".join(nav_items), sections="\n".join(sections), count=len(files))
    with open(os.path.join(HERE, "index.html"), "w", encoding="utf-8") as f:
        f.write(index)
    print(f"built index.html + {len(files)} standalone pages from {len(files)} source report(s)")


if __name__ == "__main__":
    main()
